name: Ruby Tests

on:
  push:
    paths:
      - "ruby/**"
      - ".github/workflows/ruby-tests.yml"
  pull_request:
    paths:
      - "ruby/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ruby
      - run: bundle exec rspec
